export type Attribute = "strength" | "agility" | "intelligence" | "universal";

export interface Hero {
  id: number;
  name: string;
  displayName: string;
  attribute: Attribute;
  roles: string[];
}

const CDN = "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes";

export function heroImageUrl(name: string): string {
  return `${CDN}/${name}.png`;
}

export const HEROES: Hero[] = [
  // Strength
  { id: 1, name: "axe", displayName: "Axe", attribute: "strength", roles: ["Carry", "Initiator", "Durable"] },
  { id: 2, name: "beastmaster", displayName: "Beastmaster", attribute: "strength", roles: ["Initiator", "Jungler", "Disabler"] },
  { id: 3, name: "brewmaster", displayName: "Brewmaster", attribute: "strength", roles: ["Initiator", "Disabler", "Durable"] },
  { id: 4, name: "bristleback", displayName: "Bristleback", attribute: "strength", roles: ["Carry", "Durable", "Nuker"] },
  { id: 5, name: "centaur", displayName: "Centaur Warrunner", attribute: "strength", roles: ["Initiator", "Durable", "Disabler"] },
  { id: 6, name: "chaos_knight", displayName: "Chaos Knight", attribute: "strength", roles: ["Carry", "Durable", "Disabler"] },
  { id: 7, name: "dragon_knight", displayName: "Dragon Knight", attribute: "strength", roles: ["Carry", "Durable", "Initiator"] },
  { id: 8, name: "earth_spirit", displayName: "Earth Spirit", attribute: "strength", roles: ["Initiator", "Disabler", "Nuker"] },
  { id: 9, name: "earthshaker", displayName: "Earthshaker", attribute: "strength", roles: ["Initiator", "Disabler", "Support"] },
  { id: 10, name: "elder_titan", displayName: "Elder Titan", attribute: "strength", roles: ["Initiator", "Disabler", "Support"] },
  { id: 11, name: "huskar", displayName: "Huskar", attribute: "strength", roles: ["Carry", "Durable", "Nuker"] },
  { id: 12, name: "wisp", displayName: "Io", attribute: "strength", roles: ["Support", "Nuker", "Disabler"] },
  { id: 13, name: "kunkka", displayName: "Kunkka", attribute: "strength", roles: ["Carry", "Support", "Initiator"] },
  { id: 14, name: "legion_commander", displayName: "Legion Commander", attribute: "strength", roles: ["Carry", "Initiator", "Jungler"] },
  { id: 15, name: "life_stealer", displayName: "Lifestealer", attribute: "strength", roles: ["Carry", "Jungler", "Durable"] },
  { id: 16, name: "lycan", displayName: "Lycan", attribute: "strength", roles: ["Carry", "Pusher", "Jungler"] },
  { id: 17, name: "magnataur", displayName: "Magnus", attribute: "strength", roles: ["Initiator", "Disabler", "Nuker"] },
  { id: 18, name: "mars", displayName: "Mars", attribute: "strength", roles: ["Initiator", "Disabler", "Durable"] },
  { id: 19, name: "night_stalker", displayName: "Night Stalker", attribute: "strength", roles: ["Carry", "Disabler", "Initiator"] },
  { id: 20, name: "omniknight", displayName: "Omniknight", attribute: "strength", roles: ["Support", "Durable"] },
  { id: 21, name: "phoenix", displayName: "Phoenix", attribute: "strength", roles: ["Support", "Disabler", "Initiator"] },
  { id: 22, name: "pudge", displayName: "Pudge", attribute: "strength", roles: ["Support", "Disabler", "Initiator"] },
  { id: 23, name: "sand_king", displayName: "Sand King", attribute: "strength", roles: ["Initiator", "Disabler", "Support"] },
  { id: 24, name: "slardar", displayName: "Slardar", attribute: "strength", roles: ["Carry", "Initiator", "Disabler"] },
  { id: 25, name: "spirit_breaker", displayName: "Spirit Breaker", attribute: "strength", roles: ["Carry", "Initiator", "Disabler"] },
  { id: 26, name: "sven", displayName: "Sven", attribute: "strength", roles: ["Carry", "Disabler", "Initiator"] },
  { id: 27, name: "tidehunter", displayName: "Tidehunter", attribute: "strength", roles: ["Initiator", "Durable", "Disabler"] },
  { id: 28, name: "tiny", displayName: "Tiny", attribute: "strength", roles: ["Carry", "Initiator", "Nuker"] },
  { id: 29, name: "treant", displayName: "Treant Protector", attribute: "strength", roles: ["Support", "Disabler", "Initiator"] },
  { id: 30, name: "tusk", displayName: "Tusk", attribute: "strength", roles: ["Initiator", "Disabler", "Support"] },
  { id: 31, name: "abyssal_underlord", displayName: "Underlord", attribute: "strength", roles: ["Carry", "Support", "Pusher"] },
  { id: 32, name: "undying", displayName: "Undying", attribute: "strength", roles: ["Support", "Durable", "Nuker"] },
  { id: 33, name: "skeleton_king", displayName: "Wraith King", attribute: "strength", roles: ["Carry", "Durable", "Disabler"] },
  // Agility
  { id: 34, name: "antimage", displayName: "Anti-Mage", attribute: "agility", roles: ["Carry", "Escape"] },
  { id: 35, name: "arc_warden", displayName: "Arc Warden", attribute: "agility", roles: ["Carry", "Pusher", "Nuker"] },
  { id: 36, name: "bloodseeker", displayName: "Bloodseeker", attribute: "agility", roles: ["Carry", "Jungler", "Initiator"] },
  { id: 37, name: "bounty_hunter", displayName: "Bounty Hunter", attribute: "agility", roles: ["Carry", "Support", "Escape"] },
  { id: 38, name: "broodmother", displayName: "Broodmother", attribute: "agility", roles: ["Carry", "Escape", "Pusher"] },
  { id: 39, name: "clinkz", displayName: "Clinkz", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 40, name: "drow_ranger", displayName: "Drow Ranger", attribute: "agility", roles: ["Carry", "Disabler"] },
  { id: 41, name: "ember_spirit", displayName: "Ember Spirit", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 42, name: "faceless_void", displayName: "Faceless Void", attribute: "agility", roles: ["Carry", "Initiator", "Disabler"] },
  { id: 43, name: "gyrocopter", displayName: "Gyrocopter", attribute: "agility", roles: ["Carry", "Nuker", "Pusher"] },
  { id: 44, name: "juggernaut", displayName: "Juggernaut", attribute: "agility", roles: ["Carry", "Escape", "Pusher"] },
  { id: 45, name: "luna", displayName: "Luna", attribute: "agility", roles: ["Carry", "Pusher", "Nuker"] },
  { id: 46, name: "medusa", displayName: "Medusa", attribute: "agility", roles: ["Carry", "Durable", "Nuker"] },
  { id: 47, name: "meepo", displayName: "Meepo", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 48, name: "mirana", displayName: "Mirana", attribute: "agility", roles: ["Carry", "Support", "Escape"] },
  { id: 49, name: "morphling", displayName: "Morphling", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 50, name: "naga_siren", displayName: "Naga Siren", attribute: "agility", roles: ["Carry", "Support", "Disabler"] },
  { id: 51, name: "phantom_assassin", displayName: "Phantom Assassin", attribute: "agility", roles: ["Carry", "Escape"] },
  { id: 52, name: "phantom_lancer", displayName: "Phantom Lancer", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 53, name: "razor", displayName: "Razor", attribute: "agility", roles: ["Carry", "Durable", "Pusher"] },
  { id: 54, name: "riki", displayName: "Riki", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 55, name: "slark", displayName: "Slark", attribute: "agility", roles: ["Carry", "Escape"] },
  { id: 56, name: "sniper", displayName: "Sniper", attribute: "agility", roles: ["Carry", "Nuker"] },
  { id: 57, name: "spectre", displayName: "Spectre", attribute: "agility", roles: ["Carry", "Escape", "Durable"] },
  { id: 58, name: "templar_assassin", displayName: "Templar Assassin", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  { id: 59, name: "terrorblade", displayName: "Terrorblade", attribute: "agility", roles: ["Carry", "Escape", "Pusher"] },
  { id: 60, name: "troll_warlord", displayName: "Troll Warlord", attribute: "agility", roles: ["Carry", "Disabler", "Escape"] },
  { id: 61, name: "ursa", displayName: "Ursa", attribute: "agility", roles: ["Carry", "Jungler", "Initiator"] },
  { id: 62, name: "vengefulspirit", displayName: "Vengeful Spirit", attribute: "agility", roles: ["Support", "Disabler", "Initiator"] },
  { id: 63, name: "viper", displayName: "Viper", attribute: "agility", roles: ["Carry", "Nuker", "Durable"] },
  { id: 64, name: "weaver", displayName: "Weaver", attribute: "agility", roles: ["Carry", "Escape", "Nuker"] },
  // Intelligence
  { id: 65, name: "ancient_apparition", displayName: "Ancient Apparition", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 66, name: "bane", displayName: "Bane", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 67, name: "batrider", displayName: "Batrider", attribute: "intelligence", roles: ["Initiator", "Disabler", "Nuker"] },
  { id: 68, name: "chen", displayName: "Chen", attribute: "intelligence", roles: ["Support", "Pusher", "Jungler"] },
  { id: 69, name: "crystal_maiden", displayName: "Crystal Maiden", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 70, name: "dark_seer", displayName: "Dark Seer", attribute: "intelligence", roles: ["Support", "Initiator", "Jungler"] },
  { id: 71, name: "dark_willow", displayName: "Dark Willow", attribute: "intelligence", roles: ["Support", "Disabler", "Escape"] },
  { id: 72, name: "dazzle", displayName: "Dazzle", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 73, name: "death_prophet", displayName: "Death Prophet", attribute: "intelligence", roles: ["Carry", "Pusher", "Nuker"] },
  { id: 74, name: "disruptor", displayName: "Disruptor", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 75, name: "doom_bringer", displayName: "Doom", attribute: "intelligence", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 76, name: "enchantress", displayName: "Enchantress", attribute: "intelligence", roles: ["Support", "Pusher", "Jungler"] },
  { id: 77, name: "grimstroke", displayName: "Grimstroke", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 78, name: "invoker", displayName: "Invoker", attribute: "intelligence", roles: ["Carry", "Nuker", "Escape"] },
  { id: 79, name: "jakiro", displayName: "Jakiro", attribute: "intelligence", roles: ["Support", "Pusher", "Disabler"] },
  { id: 80, name: "keeper_of_the_light", displayName: "Keeper of the Light", attribute: "intelligence", roles: ["Support", "Nuker", "Pusher"] },
  { id: 81, name: "leshrac", displayName: "Leshrac", attribute: "intelligence", roles: ["Carry", "Nuker", "Pusher"] },
  { id: 82, name: "lich", displayName: "Lich", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 83, name: "lina", displayName: "Lina", attribute: "intelligence", roles: ["Carry", "Support", "Nuker"] },
  { id: 84, name: "lion", displayName: "Lion", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 85, name: "furion", displayName: "Nature's Prophet", attribute: "intelligence", roles: ["Carry", "Pusher", "Jungler"] },
  { id: 86, name: "necrolyte", displayName: "Necrophos", attribute: "intelligence", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 87, name: "nevermore", displayName: "Shadow Fiend", attribute: "intelligence", roles: ["Carry", "Nuker"] },
  { id: 88, name: "nyx_assassin", displayName: "Nyx Assassin", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 89, name: "obsidian_destroyer", displayName: "Outworld Destroyer", attribute: "intelligence", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 90, name: "ogre_magi", displayName: "Ogre Magi", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 91, name: "oracle", displayName: "Oracle", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 92, name: "puck", displayName: "Puck", attribute: "intelligence", roles: ["Initiator", "Escape", "Nuker"] },
  { id: 93, name: "pugna", displayName: "Pugna", attribute: "intelligence", roles: ["Support", "Nuker", "Pusher"] },
  { id: 94, name: "queenofpain", displayName: "Queen of Pain", attribute: "intelligence", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 95, name: "rubick", displayName: "Rubick", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 96, name: "shadow_demon", displayName: "Shadow Demon", attribute: "intelligence", roles: ["Support", "Disabler", "Nuker"] },
  { id: 97, name: "shadow_shaman", displayName: "Shadow Shaman", attribute: "intelligence", roles: ["Support", "Disabler", "Pusher"] },
  { id: 98, name: "silencer", displayName: "Silencer", attribute: "intelligence", roles: ["Carry", "Support", "Disabler"] },
  { id: 99, name: "skywrath_mage", displayName: "Skywrath Mage", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 100, name: "storm_spirit", displayName: "Storm Spirit", attribute: "intelligence", roles: ["Carry", "Escape", "Nuker"] },
  { id: 101, name: "tinker", displayName: "Tinker", attribute: "intelligence", roles: ["Carry", "Nuker", "Pusher"] },
  { id: 102, name: "visage", displayName: "Visage", attribute: "intelligence", roles: ["Support", "Nuker", "Durable"] },
  { id: 103, name: "warlock", displayName: "Warlock", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 104, name: "windrunner", displayName: "Windranger", attribute: "intelligence", roles: ["Carry", "Support", "Escape"] },
  { id: 105, name: "witch_doctor", displayName: "Witch Doctor", attribute: "intelligence", roles: ["Support", "Nuker", "Disabler"] },
  { id: 106, name: "zuus", displayName: "Zeus", attribute: "intelligence", roles: ["Nuker", "Support"] },
  // Universal
  { id: 107, name: "abaddon", displayName: "Abaddon", attribute: "universal", roles: ["Carry", "Support", "Durable"] },
  { id: 108, name: "alchemist", displayName: "Alchemist", attribute: "universal", roles: ["Carry", "Jungler", "Durable"] },
  { id: 109, name: "dawnbreaker", displayName: "Dawnbreaker", attribute: "universal", roles: ["Carry", "Support", "Durable"] },
  { id: 110, name: "hoodwink", displayName: "Hoodwink", attribute: "universal", roles: ["Support", "Disabler", "Nuker"] },
  { id: 111, name: "lone_druid", displayName: "Lone Druid", attribute: "universal", roles: ["Carry", "Pusher", "Jungler"] },
  { id: 112, name: "marci", displayName: "Marci", attribute: "universal", roles: ["Support", "Carry", "Disabler"] },
  { id: 113, name: "monkey_king", displayName: "Monkey King", attribute: "universal", roles: ["Carry", "Escape", "Initiator"] },
  { id: 114, name: "muerta", displayName: "Muerta", attribute: "universal", roles: ["Carry", "Nuker", "Disabler"] },
  { id: 115, name: "pangolier", displayName: "Pangolier", attribute: "universal", roles: ["Carry", "Disabler", "Initiator"] },
  { id: 116, name: "primal_beast", displayName: "Primal Beast", attribute: "universal", roles: ["Initiator", "Durable", "Disabler"] },
  { id: 117, name: "snapfire", displayName: "Snapfire", attribute: "universal", roles: ["Support", "Nuker", "Disabler"] },
  { id: 118, name: "techies", displayName: "Techies", attribute: "universal", roles: ["Nuker", "Disabler"] },
  { id: 119, name: "void_spirit", displayName: "Void Spirit", attribute: "universal", roles: ["Carry", "Escape", "Nuker"] },
  { id: 120, name: "winter_wyvern", displayName: "Winter Wyvern", attribute: "universal", roles: ["Support", "Disabler", "Nuker"] },
];
